# Generated by Django 4.0.5 on 2022-07-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd_app', '0006_alter_transaction_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='delivery_date',
            field=models.CharField(max_length=15),
        ),
    ]
