# Generated by Django 3.1.2 on 2022-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipe',
            field=models.TextField(null=True),
        ),
    ]
