# Generated by Django 3.1.2 on 2022-06-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='recipe',
        ),
    ]
